const assert = require('node:assert/strict');
const {chromium} = require('playwright');
const base = process.env.SITE_URL || 'http://127.0.0.1:8000/';
(async()=>{
 const browser=await chromium.launch({executablePath:process.env.CHROMIUM_PATH||'/usr/bin/chromium',args:['--no-sandbox']});
 try{
  const page=await browser.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));
  // Synthetic ID tests media UI only. Block external navigation/network: no live-video research is claimed.
  await page.route('https://i.ytimg.com/**',route=>route.abort());
  await page.goto(base+'editor.html?gun=m4a1');
  await page.getByLabel('Skin name',{exact:true}).fill('Video UI fixture');
  await page.getByLabel('YouTube video link (optional)',{exact:true}).fill('https://youtu.be/TestVideo01?t=1m24s');
  await page.getByRole('button',{name:'Save skin',exact:true}).click();
  await page.getByText('Video UI fixture',{exact:true}).waitFor();
  let data=await page.evaluate(()=>JSON.parse(localStorage.getItem('ff-skin-vault-catalog-v1')));
  let skin=data.guns.find(g=>g.id==='m4a1').skins.at(-1);
  assert.equal(skin.videoTimestamp,84);assert.equal(skin.verified,false);assert.match(skin.source,/&t=84s$/);
  await page.goto(base+'m4a1.html');
  const card=page.locator('.skin-card').filter({hasText:'Video UI fixture'});
  await card.waitFor();assert.equal(await card.locator('.video-preview').getAttribute('href'),'https://www.youtube.com/watch?v=TestVideo01&t=84s');
  await card.getByText('Watch source · 1:24',{exact:true}).waitFor();
  assert.equal(await card.locator('.art img').count(),0);
  await page.goto(base+'editor.html?gun=m4a1');
  await page.locator('.edit-item').filter({hasText:'Video UI fixture'}).getByRole('button',{name:'Edit',exact:true}).click();
  assert.equal(await page.getByLabel('Video timestamp (optional)').inputValue(),'1:24');
  await page.getByLabel('Video timestamp (optional)').fill('2:12');
  await page.getByRole('button',{name:'Update skin'}).click();
  data=await page.evaluate(()=>JSON.parse(localStorage.getItem('ff-skin-vault-catalog-v1')));skin=data.guns.find(g=>g.id==='m4a1').skins.at(-1);
  assert.equal(skin.videoTimestamp,132);assert.match(skin.source,/&t=132s$/);
  await page.getByLabel('Skin name',{exact:true}).fill('Invalid video fixture');
  await page.getByLabel('YouTube video link (optional)').fill('https://www.youtube.com.evil.test/watch?v=TestVideo01');
  await page.getByRole('button',{name:'Save skin',exact:true}).click();
  await page.getByRole('status').filter({hasText:'Enter a YouTube'}).waitFor();
  await page.getByLabel('YouTube video link (optional)').fill('https://youtu.be/TestVideo01?t=invalid');
  await page.getByRole('button',{name:'Save skin',exact:true}).click();
  await page.getByRole('status').filter({hasText:'Enter a YouTube'}).waitFor();
  await page.getByLabel('YouTube video link (optional)').fill('https://www.youtube.com/shorts/TestVideo01');
  await page.getByLabel('Video timestamp (optional)').fill('1:99');
  await page.getByRole('button',{name:'Save skin',exact:true}).click();
  await page.getByRole('status').filter({hasText:'Use seconds'}).waitFor();
  await page.getByLabel('Video timestamp (optional)').fill('');
  await page.getByLabel('YouTube video link (optional)').fill('https://www.youtube.com/watch?v=TestVideo02#t=2m10s');
  await page.getByRole('button',{name:'Save skin',exact:true}).click();
  await page.getByText('Invalid video fixture',{exact:true}).waitFor();
  data=await page.evaluate(()=>JSON.parse(localStorage.getItem('ff-skin-vault-catalog-v1')));assert.equal(data.guns.find(g=>g.id==='m4a1').skins.at(-1).videoTimestamp,130);
  const downloadPromise=page.waitForEvent('download');await page.getByRole('button',{name:'Export catalog'}).click();
  const download=await downloadPromise;await download.saveAs('/tmp/free-fire-video-test-export.json');
  const exported=JSON.parse(require('node:fs').readFileSync('/tmp/free-fire-video-test-export.json','utf8'));
  assert.equal(exported.guns.find(g=>g.id==='m4a1').skins.at(-1).videoTimestamp,130);
  await page.evaluate(()=>localStorage.clear());await page.reload();page.on('dialog',d=>d.accept());
  await page.getByLabel('Import a catalog backup').setInputFiles('/tmp/free-fire-video-test-export.json');
  await page.getByLabel('Gun',{exact:true}).selectOption('m4a1');await page.goto(base+'m4a1.html');
  await page.locator('.skin-card').filter({hasText:'Invalid video fixture'}).getByText('Watch source · 2:10',{exact:true}).waitFor();
  await page.setViewportSize({width:320,height:800});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);
  await page.evaluate(()=>localStorage.clear());await page.goto(base+'mp40.html');
  await page.getByRole('link',{name:'Find videos on YouTube',exact:true}).waitFor();
  assert.match(await page.getByRole('link',{name:'Find videos on YouTube',exact:true}).getAttribute('href'),/youtube.com\/results\?search_query=/);
  assert.deepEqual(errors,[]);
  console.log('PASS: YouTube URL validation, timestamp save/edit, source synchronization, unavailable thumbnails, separate skin artwork, unverified default, empty-collection video search.');
 }finally{await browser.close();}
})().catch(e=>{console.error(e);process.exitCode=1;});
